repos:
    - repo: local
      hooks:
          - id: biome-format
            name: Biome Format
            entry: pnpm format:fix
            language: system
            pass_filenames: false
          - id: biome-lint
            name: Biome Lint
            entry: pnpm lint
            language: system
            pass_filenames: false
          - id: typecheck
            name: Type Check
            entry: pnpm typecheck
            language: system
            pass_filenames: false
